-- MySQL Script generated by MySQL Workbench
-- Sun Oct 20 09:52:11 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbsistemaLaravel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsistemaLaravel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistemaLaravel` DEFAULT CHARACTER SET utf8 ;
USE `dbsistemaLaravel` ;

-- -----------------------------------------------------
-- Table `dbsistemaLaravel`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistemaLaravel`.`Categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(256) NOT NULL,
  `descricao` VARCHAR(256) NULL,
  `condicao` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
